import HautevilleHouse.DiscreteDifferentialGeometryLemmaCanonicalLaneLean.DiscreteCurvature
import HautevilleHouse.DiscreteDifferentialGeometryLemmaCanonicalLaneLean.DiscreteConnection
import HautevilleHouse.DiscreteDifferentialGeometryLemmaCanonicalLaneLean.DiscreteIndexTheorem
import HautevilleHouse.DiscreteDifferentialGeometryLemmaCanonicalLaneLean.DiscreteHolonomy
import HautevilleHouse.DiscreteDifferentialGeometryLemmaCanonicalLaneLean.DiscreteLaplaceBeltrami
import HautevilleHouse.DiscreteDifferentialGeometryLemmaCanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace DiscreteDifferentialGeometryLemmaCanonicalLaneLean

-- This module aggregates all domain-specific files.

end DiscreteDifferentialGeometryLemmaCanonicalLaneLean
end HautevilleHouse